--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: "Two Instances in an AS Group"
Mappings:
  AWSAMI:
    us-west-2:
      ID: ami-f173cc91
Parameters:
  KeyPair:
    Description: Key Pair for AS Group Servers
    Type: String
Resources:
  ASGroup: 
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      DesiredCapacity: "2"
      LaunchConfigurationName: "LaunchConfiguration"
      MaxSize: "2"
      MinSize: "0"
      Tags: 
        -
          Key: Name
          PropagateAtLaunch: true
          Value: ASGroup
      VPCZoneIdentifier: 
        - vpc-2f84c848

  LaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      KeyName:
        Ref: "KeyPair"
      ImageId:
        Fn::FindInMap: [ AWSAMI, !Ref "AWS::Region", "ID" ]
      IamInstanceProfile:
        Name: "ServerRole"
      UserData:
        Fn::Base64: !Join ['',[
          "#!/bin/bash\n
          echo 'Change memory Buffers'\n
          sysctl -w net.core.rmem_max=26214400\n
          sysctl -w net.core.rmem_default=26214400\n
          sysctl -w net.ipv4.udp_mem='524288 1048576 26214400'\n
          sysctl -w net.ipv4.udp_rmem_min=524288\n
          "]]
      SecurityGroups:
        - Ref: "AutoScalingSG"
      InstanceType: t2.micro

  AutoScalingSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from all
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-${AccountName}-VPC"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: '53'
        ToPort: '53'
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: '8'
        ToPort: '-1'
        CidrIp: 0.0.0.0/0