---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for Root-access account alerts."
Parameters:
  Account:
    Description: "Name of the P&G Account (e.g. Enterprise, Security, etc)."
    Type: String
  Environment:
    Description: "Environment in question."
    Type: String
    AllowedValues:
      - PROD
      - DR
      - NONPROD
  Region:
    Description: "Region in question."
    Type: String
    AllowedValues:
      - US-EAST-1
      - US-EAST-2 #used for DR
      - EU-CENTRAL-1
      - AP-SOUTHEAST-1
  NotificationsEmail: 
    Description: "Email address to notify when new logs are published."
    Type: String
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: "AWS::S3::Bucket"
    Properties: {}
  BucketPolicy:
    DependsOn: S3Bucket
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: 
        Ref: S3Bucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AWSCloudTrailAclCheck"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.us-east-1.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: 
              !Sub |-
                arn:aws:s3:::${S3Bucket}
          -
            Sid: "AWSCloudTrailWrite"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.us-east-1.amazonaws.com"
            Action: "s3:PutObject"
            Resource:
              !Sub |-
                arn:aws:s3:::${S3Bucket}/AWSLogs/RootAccess/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
  Topic:
    DependsOn: BucketPolicy
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription: #subscription defined inline
        -
          Endpoint:
            Ref: NotificationsEmail
          Protocol: email
      TopicName: "RootKeyAccessNotification"
  TopicPolicy:
    DependsOn: Topic
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - Ref: "Topic"
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          -
            Sid: "AWSCloudTrailSNSPolicy"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.us-east-1.amazonaws.com"
            Resource: "*"
            Action: "sns:Publish"
  LogGroup: 
    Type: "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName: "DefaultLogGroup"
      RetentionInDays: 7
  MetricFilter:
    DependsOn: 
      - LogGroup
    Type: "AWS::Logs::MetricFilter"
    Properties: 
      FilterPattern: "{ $.userIdentity.type = \"Root\" && $.userIdentity.invokedBy NOT EXISTS && $.eventType != \"AwsServiceEvent\" }"
      LogGroupName: "DefaultLogGroup"
      MetricTransformations:
        - 
          MetricValue: "1"
          MetricNamespace: "CloudTrailMetrics"
          MetricName: "RootAccountUsageCount"
  Trail:
    DependsOn:
      - BucketPolicy
      - TopicPolicy
    Type: "AWS::CloudTrail::Trail"
    Properties:
      IsMultiRegionTrail: false #means trail is created only in the region of the stack
      S3BucketName: 
        Ref: S3Bucket
      SnsTopicName: 
        Fn::GetAtt: 
          - Topic
          - TopicName
      IsLogging: true
  Alarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ActionsEnabled: true
      AlarmDescription: "Notifies when someone logs in using Root account"
      AlarmName: "Root account usage alarm"
      AlarmActions:
        - Ref: "Topic"
      MetricName: "RootAccountUsageCount"
      Namespace: "CloudTrailMetrics"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 60 #seconds = 1min
      Statistic: "Sum"
      Threshold: 0
      Unit: "Seconds"
  